---
title: Processing Affymetrix Microarrays
output: 
    html_document:
        code_folding: show
params:
    test_value: 10
---

### Import Packages
```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")

# BiocManager::install("oligo")
#package for reading CEL files, will add more packages for further steps
```
### Import Raw Data
```{r}
csv_file <- read.table(file = r"(C:\Users\linde\OneDrive\Desktop\affy_processing\data_runsheets\GLDS_25_runsheet.csv)", 
                       sep=",",
                       header = TRUE,
                       check.names = FALSE
                       )
array_data_files <- csv_file["Characteristics:  array data file"]
#access folder
#make a list?
#go through the items 
#map?
#raw_data = list(map(lambda x: affyio::read.celfile(x, intensity.means.only=FALSE), unread_data))
#raw_data <- affyio::read.celfile(array_data_files,intensity.means.only=FALSE)
raw_data <- oligo::read.celfiles(filenames = r"(C:\Users\linde\rmarkdown\input_data\GLDS25\GLDS-25_array_Mmus_C57-6CR_LVR_FLT_Rep1_Sample52_raw.CEL.gz)")
```

### Verify Data
```{r}
print("Verify Data step")
```
### Normalize Data
```{r}
print("Normalize Data step")
```
### Verify Normalization
```{r}
print("Verify Normalization step")
```
### DGE Analysis
```{r}
print("DGE Analysis step")
```
### Gene Annotations
```{r}
print("Gene Annotations step")
```